### ISSUE TITLE
Spyder plugin breaks Spyder on Anaconda

### ISSUE THREAD

**Issue by sunil-subbakrishna** [lifelib-dev/lifelib#51]
I installed lifelib using conda and started up Spyder without a problem. Then I installed the Spyder plugin using conda, and Spyder initiates but doesn't complete the startup. I am using Spyder 5.4.2 under Python 3.11. I was able to capture the error messages which are below. When I uninstall the plugin, it works again. Any suggestions?

modelx_plugin: cannot import name 'PY2' from 'spyder.py3compat' (C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\py3compat.py)
Traceback (most recent call last):
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\app\find_plugins.py", line 67, in find_external_plugins
mod = importlib.import_module(entry_point.module_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\importlib\__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 1206, in _gcd_import
File "", line 1178, in _find_and_load
File "", line 1128, in _find_and_load_unlocked
File "", line 241, in _call_with_frames_removed
File "", line 1206, in _gcd_import
File "", line 1178, in _find_and_load
File "", line 1128, in _find_and_load_unlocked
File "", line 241, in _call_with_frames_removed
File "", line 1206, in _gcd_import
File "", line 1178, in _find_and_load
File "", line 1149, in _find_and_load_unlocked
File "", line 690, in _load_unlocked
File "", line 940, in exec_module
File "", line 241, in _call_with_frames_removed
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder_modelx\__init__.py", line 25, in 
from .plugins.mxplugin import ModelxPlugin
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder_modelx\plugins\mxplugin.py", line 51, in 
from .mxplugin_5_3 import ModelxPlugin_5_3 as ModelxPlugin
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder_modelx\plugins\mxplugin_5_3.py", line 5, in 
from .mxconsole_5_3 import MxConsoleAPI_5_3
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder_modelx\plugins\mxconsole_5_3.py", line 14, in 
from spyder.py3compat import is_string, PY2, to_text_string
ImportError: cannot import name 'PY2' from 'spyder.py3compat' (C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\py3compat.py)
mxdataviewer: cannot import name 'PY2' from 'spyder.py3compat' (C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\py3compat.py)
Traceback (most recent call last):
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\app\find_plugins.py", line 67, in find_external_plugins
mod = importlib.import_module(entry_point.module_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\importlib\__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 1206, in _gcd_import
File "", line 1178, in _find_and_load
File "", line 1149, in _find_and_load_unlocked
File "", line 690, in _load_unlocked
File "", line 940, in exec_module
File "", line 241, in _call_with_frames_removed
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder_modelx\plugins\dataview_plugin.py", line 63, in 
from spyder_modelx.widgets.mxdataviewer.dataframeviewer import MxDataFrameViewer
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder_modelx\__init__.py", line 25, in 
from .plugins.mxplugin import ModelxPlugin
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder_modelx\plugins\mxplugin.py", line 51, in 
from .mxplugin_5_3 import ModelxPlugin_5_3 as ModelxPlugin
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder_modelx\plugins\mxplugin_5_3.py", line 5, in 
from .mxconsole_5_3 import MxConsoleAPI_5_3
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder_modelx\plugins\mxconsole_5_3.py", line 14, in 
from spyder.py3compat import is_string, PY2, to_text_string
ImportError: cannot import name 'PY2' from 'spyder.py3compat' (C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\py3compat.py)
: Plugin "modelx_plugin" not found!
Traceback (most recent call last):
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\app\mainwindow.py", line 796, in setup
plugin_instance = PLUGIN_REGISTRY.register_plugin(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\api\plugin_registration\registry.py", line 342, in register_plugin
instance = self._instantiate_spyder5_plugin(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\api\plugin_registration\registry.py", line 193, in _instantiate_spyder5_plugin
plugin_instance.initialize()
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\api\plugins\new_api.py", line 679, in initialize
self.on_initialize()
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder_modelx\plugins\analyzer_plugin.py", line 194, in on_initialize
self.get_plugin('modelx_plugin').get_container().set_child_plugin('analyzer', self.get_container())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\api\plugins\new_api.py", line 442, in get_plugin
raise e
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\api\plugins\new_api.py", line 437, in get_plugin
return self._main.get_plugin(plugin_name, error=error)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\app\mainwindow.py", line 356, in get_plugin
raise SpyderAPIError(f'Plugin "{plugin_name}" not found!')
spyder.api.exceptions.SpyderAPIError: Plugin "modelx_plugin" not found!
Traceback (most recent call last):
File "C:\Users\sunil\anaconda3\envs\LifeLib\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
^^^^^^
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\app\start.py", line 257, in main
mainwindow.main(options, args)
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\app\mainwindow.py", line 1823, in main
mainwindow = create_window(MainWindow, app, splash, options, args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\app\utils.py", line 300, in create_window
main.post_visible_setup()
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\app\mainwindow.py", line 1013, in post_visible_setup
self.layouts.on_mainwindow_visible()
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\plugins\layout\plugin.py", line 203, in on_mainwindow_visible
self.create_plugins_menu()
File "C:\Users\sunil\anaconda3\envs\LifeLib\Lib\site-packages\spyder\plugins\layout\plugin.py", line 908, in create_plugins_menu
action.setChecked(plugin.dockwidget.isVisible())
^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'isVisible'

**Comment by fumitoh** [comment]
You must have installed Spyder 5.4.3, not Spyder 5.4.2. The most recent version of spyder-modelx,  version 0.13.3, supports Spyder [up to  version 5.4.2](https://docs.modelx.io/en/latest/releases/spymx_relnotes_v0.13.html#release-mxplugin-v0-13-3). I'll try to update spyder-modelx to support Spyder 5.4.3 in a few days.

**Comment by fumitoh** [comment]
spyder-modelx v0.13.4 is just released to support Spyder 5.4.3. Now you can do `conda update spyder-modelx` to update the plugin.
