### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by bakj1979** [lifelib-dev/lifelib#58]
Hello, I am running into an issue with pandas 2.1.1 when using Lifelib because .iteritems has been depreciated. Are you planning on replacing this with .items or some other fix?

Thx

**Comment by fumitoh** [comment]
Where in lifelib is `.iteritems` used?

**Comment by bakj1979** [comment]
Hi,It is in BasicTerm_S. Thx Regards,Jeffrey On 22 Oct 2023, at 02:38, fumitoh ***@***.***> wrote:﻿
Where in lifelib is .iteritems used?

**Comment by fumitoh** [comment]
@bakj1979 Can you show the error traceback?

**Comment by bakj1979** [comment]
Traceback (most recent call last):
  File "/Users/jeffreybaker/miniforge3/envs/spyder-env_actuarial/lib/python3.10/site-packages/spyder_modelx/plugins/dataview_plugin.py", line 244, in update_data
    self.update_value(val)
  File "/Users/jeffreybaker/miniforge3/envs/spyder-env_actuarial/lib/python3.10/site-packages/spyder_modelx/plugins/dataview_plugin.py", line 257, in update_value
    self.widget.setup_and_check(data)
  File "/Users/jeffreybaker/miniforge3/envs/spyder-env_actuarial/lib/python3.10/site-packages/spyder_modelx/widgets/mxdataviewer/dataframeviewer.py", line 939, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "/Users/jeffreybaker/miniforge3/envs/spyder-env_actuarial/lib/python3.10/site-packages/spyder_modelx/widgets/mxdataviewer/dataframeviewer.py", line 137, in __init__
    self.max_min_col_update()
  File "/Users/jeffreybaker/miniforge3/envs/spyder-env_actuarial/lib/python3.10/site-packages/spyder_modelx/widgets/mxdataviewer/dataframeviewer.py", line 246, in max_min_col_update
    for dummy, col in self.df.iteritems():
  File "/Users/jeffreybaker/miniforge3/envs/spyder-env_actuarial/lib/python3.10/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'iteritems'. Did you mean: 'isetitem'?

**Comment by fumitoh** [comment]
The error is raised in spyder-modelx, so I opened a issue here: https://github.com/fumitoh/spyder-modelx/issues/13
This will be fixed by the next spyder-modelx release.

**Comment by fumitoh** [comment]
spyder-modelx 0.13.5 has been released and this issue has been fixed.
